### ISSUE TITLE
Скласти блок контактної інформації

### ISSUE THREAD

**Issue by Lord-M** [Lord-M/homepage#5]
Посилання на соцмережі (Facebook чи Instagram, тощо), номер телефону чи адреса електронної скриньки, тощо. Може не всі лінки в світі, а тільки ті, що дійсно доречні.

**Comment by Mike-44** [comment]
- I’m the most successful person ever to run for the presidency, by far. Nobody’s ever been more successful than me. I’m the most successful person ever to run. Ross Perot isn’t successful like me. Romney — I have a Gucci store that’s worth more than Romney. Sorry losers and haters, but my IQ is one of the highest - and you all know it! Please don't feel so stupid or insecure, it's not your fault.

**Comment by Lord-M** [comment]
Thank you. You’re so helpful)
