### ISSUE TITLE
Скласти таймлайн

### ISSUE THREAD

**Issue by Lord-M** [Lord-M/homepage#6]
Скласти список всіх (важливих) життєвих подій, визначних дат, досягнень, періодів, що дали приємний і неприємний досвід, тощо. В цьому конкретному випадку довгих списків не буває, натомість бувають погано згорнуті, тому пакуємо сюди все підряд, а про "лишні" події можна буде промовчати пізніше. Список повинен бути систематизованим і посортованим в такий спосіб, щоб читач швидко зрозумів "паттерн" і міг легко орієнтуватись в просторі і часі цього резюме.

**Comment by Mike-44** [comment]
- I’m the most successful person ever to run for the presidency, by far. Nobody’s ever been more successful than me. I’m the most successful person ever to run. Ross Perot isn’t successful like me. Romney — I have a Gucci store that’s worth more than Romney. Sorry losers and haters, but my IQ is one of the highest - and you all know it! Please don't feel so stupid or insecure, it's not your fault.

**Comment by Lord-M** [comment]
Thanks a lot))
